import os
# os.system('yum update -y')
# os.system('yum install wget -y')
# os.system('yum install git -y')
# os.system('cd / && wget https://golang.org/dl/go1.16.5.linux-amd64.tar.gz')
# os.system('tar -C /usr/local -xzf /go1.16.5.linux-amd64.tar.gz')
# os.system('export PATH=$PATH:/usr/local/go/bin')
# os.system('source ~/.bash_profile')
# os.system('go version')
os.system('go get -u github.com/gin-gonic/gin')